### ISSUE TITLE
Checklist para mentores

### ISSUE THREAD

**Issue by mablan** [mablan/sandbox#2]
**ixops**
- [ ] Tiene su hoja de horas
- [ ] Tiene acceso a las hojas de ixpantia y de los proyectos en los que esta involucrado
- [ ] Sabe como anotar correctamente las horas
- [ ]  Conoces algunas de las estrategias que usan tus compañeros para llevar al día las horas
- [ ]  Conoce como ingresar y validar sus horas en ixops
- [ ] Sabes que es necesario tener las horas de la semana al día al finalizar el viernes o a más tardar antes de las 8:00 del lunes siguiente 

**Buenas prácticas ixpantia**
- [ ] Conversaste sobre la puntualidad en las reuniones y la importancia de cumplir los acuerdos
- [ ] Recomendaste el uso de un gestor de contraseñas y conversaste sobre buenas prácticas de manejo de secretos
- [ ] Conversaste sobre la importancia de no trabajar con datos del cliente en tu computador local
- [ ] Conversaste sobre algunas de las estrategias que usamos para estimar el tiempo que nos va a tomar realizar una tarea
- [ ]  Sabes como agendar tareas y reuniones en el calendario

**Documentacion**
- [ ] Sabes hacer un reporte en Quarto
- [ ] Conoce como publicar a connect
- [ ]  Sabes como usar publica_wiki

**ixplaza**
- [ ] Conoce como encender y apagar ixplaza
- [ ] Conoce como descargar datos de ixplaza a tu computador
- [ ] Conoces como leer datos de una base de datos a ixplaza 
- [ ] Conoces como leer y escribir datos desde y hacia un bucket a ixplaza
- [ ] Tienes acceso a 
- [ ] Conoces como moverte de forma básica en la terminal (`ls`, `cp`, `mv`, `history`, etc.)
- [ ] Sabes como instalar un paquete o dependencia en linux 

**onboarding**
- [ ] Tienes un repo de onboarding
- [ ] Tienes ticketes  en ese repo documentando las cosas que estas aprendiendo
- [ ] Tienes un proyecto interno al que contribuir con tareas específicas definidas
- [ ] Tienes un proyecto de cliente en el que participas inicialmente de forma silenciosa
- [ ] Conoces el codex y como usarlo
- [ ] Conoces que puedes participar en:
   - La ventanilla
   - El masterclass
   - El espacio de los sábados de onboarding
   - El club de ingeniería de datos 

**ixplorer**
- [ ] Has revisado el libro de DataOps
- [ ] Sabes como crear un nuevo proyecto y repositorio
- [ ] Sabes como bifucar y clonar tu repo en ixplaza
- [ ] Sabes como trabajar en ramas y en función de tiquetes
- [ ] Sabes como hacer tiquetes
- [ ] Sabes como hacer una SF
- [ ] Sabes como revisar y aceptar una SF
- [ ] Sabes como hacer comentarios de forma constructiva sobre el código
- [ ] Entiendes que el código que ofreces en una SF esta listo y cualquier otro miembro del equipo debería de ser capaz de ejecutarlo sin problema
- [ ] Sabes que para mostrar avance hay que hacer tiquetes y documentar lo que estas haciendo

**zoom**
- [ ] Tienes tu propia sala zoom
- [ ] Sabes que hacer si necesitas utilizar una de las salas más grandes
- [ ] Sabes a donde van las grabaciones de las sesiones de zoom en las salas más grandes
